### ISSUE TITLE
I can't delete stacks using phone. 

### ISSUE THREAD

**Issue by danielchao** [ericl/Kansas#5]
Uncaught TypeError: Object #<HTMLImageElement> has no method 'prop' kview.js:51
toId kview.js:51
v.extend.map jquery-1.8.3.min.js:2
KansasUI._removeCard kansasui.js:1042
(anonymous function) kansasui.js:2260
v.event.dispatch jquery-1.8.3.min.js:2
o.handle.u

**Comment by ericl** [comment]
Resolved in 9d2963f.

**Comment by danielchao** [comment]
cool
